/* 
  This is a test file.
  When writing software, it is common good practice in software development community
  to write automated tests that, when executed, test the functionality of our code,
  and tell us if our code has any bugs.

  This file was auto-generated by `create-react-app` and we will NOT cover the topic
  of testing in our class, but it's helpful to know about it.

  More on testing:
  - https://code.tutsplus.com/articles/the-beginners-guide-to-unit-testing-what-is-unit-testing--wp-25728
  - https://medium.freecodecamp.org/the-right-way-to-test-react-components-548a4736ab22
  
  Please note: You do NOT have to read / learn about testing in this class.
  If you'd like to read more, it is encouraged.
*/
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

it('renders without crashing', () => {
  const div = document.createElement('div');
  ReactDOM.render(<App />, div);
  ReactDOM.unmountComponentAtNode(div);
});
